#!/bin/bash

# Specific aliases for working with ROS
alias rosenv='env | grep ROS | grep -v ROS_PACKAGE_PATH'
alias rospath='echo -e ${ROS_PACKAGE_PATH//:/\\n}'

# Check if we have sourced a ros workspace
path_array=()
if [[ -n "$ROSLISP_PACKAGE_DIRECTORIES" ]]; then
  # Parse catkin_workspace env variable, to get all workspaces.
  IFS=: read -r -d '' -a path_array < <(printf '%s:\0' "$ROSLISP_PACKAGE_DIRECTORIES")
fi;

source /opt/ros/indigo/setup.bash

# Source Workspace if it was previously sourced already
if [ ${#path_array[@]} -ne 0 ]; then
  for workspace in "${path_array[@]}"; do
    source "${workspace%"share/common-lisp"}"/setup.bash --extend
  done
fi

# Function to source a workspace and to set
# a env var for the prompting the workspace
# Usage: sws <workspace_name>
# All workspace names should be at home
# directory and be prefixed by ws_
function sws {
  source $HOME/ws_$1/devel/setup.bash
  export CATKIN_WORKSPACE="$HOME/ws_$1"
}

# Aliases to source the correct workspace
alias smaplab='sws maplab'
alias smuma='sws muma'
alias smav='sws mav'

path_ros="$HOME/.bash.d/ros"
ip_ros=$(cat $path_ros/ros_ip)
master_uri=$(cat $path_ros/ros_master_uri)
export ROS_IP=$ip_ros
export ROS_HOSTNAME=$ROS_IP
export ROS_MASTER_URI=http://$master_uri:11311

# Shortcut to change ROS server URI
# Usage: rosmaster [localhost|me|10.131.xx.yy] [eth0|wlan0|eth2...]
function rosmaster() {
  local ip_master=${1:-localhost}
  export ROS_MASTER_URI=http://$ip_master:11311
  echo "$ip_master" > $path_ros/ros_master_uri
}

# Shortcut to change ROS IP
# Usage: rosip [eth0|wlan0|lo|eth1...]
function rosip () {
  local interface=${1:-lo}
  local inet_addr=$(ifconfig $interface | grep "inet " | awk -F'[: ]+' '{ print $4 }')
  echo "$inet_addr" > $path_ros/ros_ip
  if [ -n "$inet_addr" ]; then
    export ROS_IP=$inet_addr
    export ROS_HOSTNAME=$ROS_IP
  else
    export ROS_IP=localhost
    export ROS_HOSTNAME=$ROS_IP
  fi
}

# Usage: cattest <package name> [OPTIONS|--no-deps|...]
function cattest() {
  catkin build $1 "${@:2}" --workspace $CATKIN_WORKSPACE --catkin-make-args run_tests
  catkin_test_results $CATKIN_WORKSPACE/build/$1 --verbose
}
