#!/bin/bash


# Tab-completion after typing cd to only suggest directories
complete -d cd

# Check https://gist.github.com/danpal/6283375
# Add completion for marks shortcuts
_completemarks() {
  local curw=${COMP_WORDS[COMP_CWORD]}
  local wordlist=$(find $MARKPATH -type l -exec basename {} \;)
  COMPREPLY=($(compgen -W '${wordlist[@]}' -- "$curw"))
  return 0
}
complete -F _completemarks jump unmark

# Enable vagrant command autocompletion for `vg` alias as well
complete -o default -F _vagrant vg

# Enable pip command autocompletion for `gpip` alias as well
complete -o default -F _pip gpip

# Enable git command  autocompletion for 'g' as well
complete -o default -o nospace -F __git g

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o default -o nospace -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;

# Source autocompletes in /etc/bash_completion for MacOS (needs brew)
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi
