#!/bin/bash

# Make vim the default editor
export EDITOR="vim"

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups
# Make some commands not show up in history
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# Pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=true

# Highlight section titles in manual pages
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Set .marks as the folder for jumping symlinks
export MARKPATH=~/.marks

# Downgrade OpenGL from 3.3 to 2.1 for VMware 3D graphics acceleration
export SVGA_VGPU10=0

#export CATKIN_WORKSPACE=~/ws_moveit

# MAVlink for mavros
#export PYTHONPATH=${PYTHONPATH}:${CATKIN_WORKSPACE}/src/mavlink-gbp-release

# QTcreator to work with catkin workspace
if [[ -n $CATKIN_WORKSPACE ]]; then
  export CURRENT_CMAKE_BUILD_DIR="$(catkin locate --workspace $CATKIN_WORKSPACE --build)"
fi

# To adapt qtcreator IDE to adapt to high resolution screen
export QT_SCALE_FACTOR=1.5

# For speeding up builds
export PATH="/usr/lib/ccache:$PATH"
