#!/bin/bash

# Specific aliases for working with ROS
alias rosenv='env | grep ROS | grep -v ROS_PACKAGE_PATH'
alias rospath='echo -e ${ROS_PACKAGE_PATH//:/\\n}'

alias catbuild='catkin build --workspace ~/catkin_ws -DCMAKE_BUILD_TYPE=RelWithDebInfo'
alias catclean='catkin clean --workspace ~/catkin_ws --yes'

alias activate='source ~/catkin_ws/devel/setup.sh'

# Shortcut to change ROS server URI
# Usage: rosmaster [localhost|me|10.131.xx.yy]
function rosmaster() {
  local q=${1:-localhost}
  local inet_addr=$(ifconfig eth0 | grep "inet " | awk -F'[: ]+' '{ print $4 }')
  if [ "$q" == "me" ] && [ -n "$inet_addr" ]; then
    q=$inet_addr
    export ROS_IP=$q
    export ROS_HOSTNAME=$q
  else
    unset ROS_IP
    unset ROS_HOSTNAME
  fi
  export ROS_MASTER_URI=http://$q:11311
}

# Source ROS Indigo
source /opt/ros/indigo/setup.bash

# Set ROS server address
#rosmaster localhost

# Source Workspace if built
if [ -f ~/catkin_ws/devel/setup.bash ]; then
  source ~/catkin_ws/devel/setup.bash
fi
