#!/bin/bash

# Set path by prepending and appending directories

# Directories to be prepended to PATH
declare -a dirs_to_prepend=(
)

# Directories to be appended to PATH
declare -a dirs_to_append=(
)

# Prepend directories to PATH
for ((index = 1; index <= ${#dirs_to_prepend}; index++)); do
    if [ -d ${dirs_to_prepend[$index]} ]; then
        # If these directories exist, then prepend them to existing PATH
        PATH="${dirs_to_prepend[$index]}:$PATH"
    fi
done

# Append directories to PATH
for ((index = 1; index <= ${#dirs_to_append}; index++)); do
    if [ -d ${dirs_to_append[$index]} ]; then
        # If these bins exist, then append them to existing PATH
        PATH="$PATH:${dirs_to_append[$index]}"
    fi
done

unset dirs_to_prepend dirs_to_append

export PATH
