#!/bin/bash

# Build Catkin project files for Eclipse
function catproject() {
pushd .
catkin_dir=~/catkin_ws 
cd $catkin_dir/build
for PROJECT in `find $catkin_dir -name .project`; do
    DIR=`dirname $PROJECT`
    echo $DIR
    cd $DIR
    awk -f $(rospack find mk)/eclipse.awk .project > .project_with_env && mv .project_with_env .project
done
popd
}
