#!/bin/bash

# Build the code with the common approach:
# mkdir build && cd build && cmake .. && make -j12 && cd ..
# Additionally accepts `clean` argument, that will run `make clean` before `make -j12`
function cbuild(){
  DIR=build

  function colored_echo(){
    echo "$bold$green $@ $reset"
  }

  colored_echo "Running cmake then make."
  if [ -d "$DIR" ]; then
    echo -e "$bold\tBuild folder exists."
  else
    echo -e "$bold\tCreating build folder."
    mkdir ${DIR}
  fi
  colored_echo "Calling cmake:"
  # TODO check cmakelists exists above ${DIR}
  cd ${DIR} && cmake ..
  # TODO check makefile exists inside ${DIR}
  if [ "$1" == "clean" ]; then
    colored_echo "Calling make clean."
    make clean
  fi
  colored_echo "Calling make:"
  make -j$(nproc) && cd ..

  unset -f colored_echo
}

